baseURL = "/"
title = "Help Adtoyp # SmartClip"
enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

enableEmoji = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
# Idioma español cambiando el 'contentDir' y 'defaultContentLanguage' a 'es' (u otro idioma que esté en i18n/xx.toml)
contentDir = "content/es"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language configuration

[languages]
# [languages.en]
# title = "Adtopy"
# description = "Docs related to Adtopy for smartclip"
# languageName ="English"
# weight = 1
# Idioma Español que tira de la carpeta i18n/es.toml
[languages.es]
title = "Adtopy"
description = "Documetacion relacionado con Adtopy (Smartclip)"
languageName ="Español"
weight = 1


# Everything below this are Site Params

[params]
# useHLJS = true
copyright = "Smartclip"
copyright_url = "https://www.smartclip.com/es"
privacy_policy = "https://www.smartclip.com/privacy-policy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/frodriguezsmartclip/docs-adtopy"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/frodriguezsmartclip/docs-adtopy"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# IMPORTANTE: Descomentando esta linea, sale la busqueda de Google custom search
#gcs_engine_id = "005428965223187693942:xqly4fybzsg"

# Enable Algolia DocSearch
#algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = '¡Genial! Nos alegramos. No obstante, estamos abiertos a escuchar nuevas mejoras. ¿Tienes alguna? <a href="https://github.com/frodriguezsmartclip/docs-adtopy/issues/new">Cuéntanos cómo podríamos mejorar.</a> Gracias! :)'
no = 'Lo sentimos. Por favor, cuéntanos <a href="https://github.com/frodriguezsmartclip/docs-adtopy/issues/new">cómo poder mejorar esta documentación</a>. Gracias!'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
# related commit: https://github.com/google/docsy/issues/122#issuecomment-588128070
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/smartclipES"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="LinkedIn"
	url = "https://www.linkedin.com/company/smartclip/"
	icon = "fab fa-linkedin"
	desc = "Follow us on LinkedIn to get the latest news!"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/frodriguezsmartclip/docs-adtopy"
	icon = "fab fa-github"
	desc = "Development takes place here!"

# Deshabilitado el markup de Goldmark de Hugo y el antiguo chroma + blackfriday
# Configuracion del config.toml aqui: https://gohugo.io/getting-started/configuration-markup/#configure-markup
# TODO: Eliminar cosas innecesarias del config.toml

# Highlighting config
#pygmentsCodeFences = true
#pygmentsUseClasses = true
# Use the new Chroma Go highlighter in Hugo.
#pygmentsUseClassic = true
#pygmentsOptions = "linenos=inline"
# See https://help.farbox.com/pygments.html
#pygmentsStyle = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
# [blackfriday]
#plainIDAnchors = true
#hrefTargetBlank = true
#angledQuotes = false
#latexDashes = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      	hardWraps = false
    	unsafe = true
    	xHTML = false