backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img/content
collections:
  - name: 'sistema-plantillas'
    label: 'Sistema de Plantillas'
    folder: 'content/es/plantillas'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Fecha publicación', name: 'date', widget: 'datetime' }
      - { label: 'LinkTitle', name: 'title', widget: 'string' }
      - { label: 'Descripcion', name: 'description', widget: 'string' }
      - { label: 'Peso de la página', name: 'weight', widget: 'integer' }